# NORMALIZATION PROBLEM:
This problem generates a random 5x5 array, calculates the mean and standard deviation, and returns the normalized version of the array.

#### Expected Input:
- A randomly generated 5x5 NumPy array.

#### Expected Output:
- The original and normalized versions of the 5x5 array.

#### Formula for Normalization:
- The normalized value for each element `X` in the array is computed using:

\[x_{\text{normalized}} = \frac{x - \text{mean}(X)}{\text{std}(X)}\]

In [6]:
# Import the NumPy library (for numerical computing) and shorten it to np 
import numpy as np

# Function to normalize a NumPy array
def normalize_array(X):
    if not isinstance(X, np.ndarray):
        return "Input is not a NumPy array."

    if X.size == 0:
        return "Array is empty."

    # Set variables to calculate the mean and standard deviation of X
    X_mean = X.mean()
    X_std = X.std()

    # Return the normalized version of X
    return (X - X_mean) / X_std

# Create a random 5x5 ndarray and store it to variable X
X = np.random.random((5, 5))

# Normalize the array
X_normalized = normalize_array(X)

# Save the normalized version of the array as 'X_normalized.npy'
np.save('X_normalized.npy', X_normalized)

# Print the original and normalized 5x5 ndarray
print("Original 5x5 ndarray: ")
print(X, "\n")
print("Normalized 5x5 ndarray: ")
print(X_normalized)

Original 5x5 ndarray: 
[[0.04511858 0.19974903 0.19065522 0.16903077 0.39697489]
 [0.5562152  0.15988821 0.68372569 0.47007683 0.18017113]
 [0.99462091 0.04848455 0.81740299 0.09895508 0.86201441]
 [0.47881258 0.32268133 0.79294602 0.13014492 0.77370524]
 [0.81820091 0.17024801 0.31420355 0.06640377 0.30802389]] 

Normalized 5x5 ndarray: 
[[-1.21161947 -0.68655505 -0.71743403 -0.79086221 -0.0168533 ]
 [ 0.52386442 -0.82190676  0.95684009  0.23137226 -0.75303393]
 [ 2.01251847 -1.20018996  1.41075583 -1.02881179  1.56223875]
 [ 0.26103547 -0.26912511  1.32770955 -0.92290334  1.26237539]
 [ 1.41346527 -0.78672894 -0.29791231 -1.1393433  -0.31889604]]


# DIVISIBLE BY 3 PROBLEM:
This problem generates a 10x10 array containing the squares of the first 100 positive integers. It identifies and outputs all elements divisible by 3.

#### Expected Input:
- A 10x10 NumPy array of squared integers.

#### Expected Output:
- The original 10x10 array and all elements divisible by 3.

In [17]:
# Import the NumPy library (for numerical computing) and shorten it to np 
import numpy as np

# Function to generate a 10x10 matrix of squared integers and find elements divisible by 3
def find_divisible_by_3():
    
    # Create a 10x10 ndarray with the first 100 positive integers, squared
    A = np.arange(1, 101).reshape(10, 10) ** 2

    # Identify all the elements that are divisible by 3
    div_by_3 = A[A % 3 == 0]

    # Return both the original array and the elements divisible by 3
    return A, div_by_3

# Generate the array and find divisible elements
A, div_by_3 = find_divisible_by_3()

# Save the result of the ndarray as 'div_by_3.npy'
np.save('div_by_3.npy', div_by_3)

# Print the original 10x10 ndarray and its elements that are divisible by 3
print("Original 10x10 ndarray: \n")
print("A = \n", A)
print("\n Elements Divisible by 3: \n", div_by_3)

Original 10x10 ndarray: 

A = 
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

 Elements Divisible by 3: 
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
